// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVXGNggcsozIhddbXubnMnXP4citMVZwg',
    appId: '1:111920544193:web:59a71c095ee65e3cff9740',
    messagingSenderId: '111920544193',
    projectId: 'medy24-d75cf',
    authDomain: 'medy24-d75cf.firebaseapp.com',
    storageBucket: 'medy24-d75cf.firebasestorage.app',
    measurementId: 'G-DNCK2EKPZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOgbQZZ7Lbt58Gstg4YnvBUcw3tRtKiIk',
    appId: '1:128696037827:android:4494d40549950074fb4d76',
    messagingSenderId: '128696037827',
    projectId: 'medy24-new',
    storageBucket: 'medy24-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnFgYnXSK-umK-ABgVu9209Urhsr6fTk8',
    appId: '1:111920544193:ios:f347bbcfc89526aaff9740',
    messagingSenderId: '111920544193',
    projectId: 'medy24-d75cf',
    storageBucket: 'medy24-d75cf.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnFgYnXSK-umK-ABgVu9209Urhsr6fTk8',
    appId: '1:111920544193:ios:f347bbcfc89526aaff9740',
    messagingSenderId: '111920544193',
    projectId: 'medy24-d75cf',
    storageBucket: 'medy24-d75cf.firebasestorage.app',
    iosBundleId: 'com.example.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVXGNggcsozIhddbXubnMnXP4citMVZwg',
    appId: '1:111920544193:web:8543f1971391379fff9740',
    messagingSenderId: '111920544193',
    projectId: 'medy24-d75cf',
    authDomain: 'medy24-d75cf.firebaseapp.com',
    storageBucket: 'medy24-d75cf.firebasestorage.app',
    measurementId: 'G-PPMSVCJ0B4',
  );
}
